name: fCTF
main: net.mikemadealarms.plugins.fCTF.SamplePlugin
version: 1.0
commands:
  test:
    description: Test command.
    usage: /<command>
  ctf:
    descripton: Main command.
    usage: /<command> <arg>